openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    <опис вашого додатку>
tags:
  # теги, що ви будете використовувати
  - name: Contacts
  description: Operations about contacts
  - name: Auth
  description: Auth opertaions

servers:
  - url: http://localhost:3000
  - url: https://contacts-server-app.onrender.com
paths:
  # тут будуть посилання на ендпоінти
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/{id}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
